//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akropol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JilFond
    {
        public int id { get; set; }
        public string Adress { get; set; }
        public string Etaj { get; set; }
        public Nullable<System.DateTime> GodPostroyki { get; set; }
        public Nullable<int> idKolKomnat { get; set; }
        public Nullable<int> idKolSanuzlov { get; set; }
        public Nullable<int> idNalichieKondic { get; set; }
        public string StoimostPoKadastru { get; set; }
        public string RinochStoimost { get; set; }
        public string ArendnayaStoimost { get; set; }
        public Nullable<int> idImage { get; set; }
    
        public virtual ImagesFonda ImagesFonda { get; set; }
        public virtual Komnati Komnati { get; set; }
        public virtual Kondicioner Kondicioner { get; set; }
        public virtual Sanuzli Sanuzli { get; set; }
    }
}
