//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akropol.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcropolEntities : DbContext
    {
        public AcropolEntities()
            : base("name=AcropolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ImagesFonda> ImagesFonda { get; set; }
        public virtual DbSet<JilFond> JilFond { get; set; }
        public virtual DbSet<Komnati> Komnati { get; set; }
        public virtual DbSet<Kondicioner> Kondicioner { get; set; }
        public virtual DbSet<Sanuzli> Sanuzli { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
